export type Letter = {
  id: string;
  label: string;
  color: string;
  sealColor: string;
  ribbonColor: string;
  content: string[];
  ps?: string;
};

export const letters: Letter[] = [
  {
    id: "miss-me",
    label: "Open when you miss me",
    color: "#f9e8ec",
    sealColor: "#c2516b",
    ribbonColor: "#e8a0b0",
    content: [
      "My love,",
      "If you're reading this, it means there's a little distance between us right now — and I want you to know that I feel it too.",
      "Close your eyes for a moment. Remember the last time we laughed until our stomachs hurt. Remember how my hand fits in yours like it was made for it.",
      "I'm not far. I'm right there in every song that reminded you of me, in every place we've talked about visiting, in every quiet moment where you thought of us.",
      "Miss me all you want — it just means what we have is real and worth missing.",
      "I'll be back before you know it. And when I am, I'm going to hug you for a very long time.",
      "All my love, always,",
      "Cindy",
    ],
    ps: "P.S. Go drink some water and eat something. I'm watching out for you even from here.",
  },
  {
    id: "proud",
    label: "Open when you're proud of yourself",
    color: "#fef3e2",
    sealColor: "#d4830a",
    ribbonColor: "#f0c060",
    content: [
      "Arthur!",
      "You did it. And I hope right now you're letting yourself feel every bit of that.",
      "I want you to know — I am not surprised. Not even a little. Because I have watched you work, struggle, doubt yourself, and keep going anyway. I've seen what you're made of.",
      "You deserve to celebrate. To be proud. To sit in this feeling for as long as you want.",
      "The world is so much better with you putting your whole heart into things.",
      "I love you — the everyday you, and the version of you that just conquered something.",
      "With so much pride,",
      "Your Cindy",
    ],
    ps: "P.S. You should treat yourself today. You've earned it.",
  },
  {
    id: "sad",
    label: "Open when you're sad",
    color: "#eef0f8",
    sealColor: "#5b6cb5",
    ribbonColor: "#9ba8d8",
    content: [
      "Hey you,",
      "Sadness is allowed here. You don't have to be okay right now.",
      "I wish I could sit with you, make you tea, and not say anything at all — just be next to you until it passes. Since I can't, this letter will have to do.",
      "You are allowed to feel heavy. You are allowed to cry. Feelings are not weaknesses. They're proof that you care deeply about your life, and that's one of the things I love most about you.",
      "This feeling will not last forever. It will shift. And when it does, I'll still be here — still yours, still rooting for you.",
      "Until then: breathe. Rest. Be gentle with yourself the way you would be with someone you love.",
      "I love you so much,",
      "Cindy",
    ],
    ps: "P.S. If you need to cry, cry. There's no version of you that I wouldn't choose.",
  },
  {
    id: "hard-day",
    label: "Open when you've had a hard day",
    color: "#f0ede8",
    sealColor: "#7a5c45",
    ribbonColor: "#b89880",
    content: [
      "Dear Arthur,",
      "Today asked a lot of you. And you got through it — even if 'getting through it' just means you survived to the end. That counts.",
      "Put the day down now. You don't have to carry it into the night.",
      "I'm thinking about you. About the way you furrow your brow when something frustrates you, and the way your whole face softens when you finally relax.",
      "You are more than your hard days. You are more than your worst moments. Tomorrow is a fresh page.",
      "Tonight: rest. That's your only job.",
      "Love you endlessly,",
      "Cindy",
    ],
    ps: "P.S. Whatever it was — it doesn't define you.",
  },
  {
    id: "cant-sleep",
    label: "Open when you can't sleep",
    color: "#ece8f4",
    sealColor: "#6b4fa0",
    ribbonColor: "#b09fd0",
    content: [
      "Hey, night owl,",
      "It's quiet and your mind won't stop, hm?",
      "Let me fill the silence a little. I'm thinking about the first time I realized how much I liked you. It wasn't one big moment — it was a hundred small ones. The way you remember details. The way you listen like you actually care. The way you make ordinary things feel special just by being there.",
      "You don't have to figure anything out tonight. The thoughts can wait until morning.",
      "Try breathing in for four counts, holding for four, out for four. Think of something soft and warm — like this letter, or the idea of us.",
      "Sleep will come. And I'll be here when morning does.",
      "Softly yours,",
      "Cindy",
    ],
    ps: "P.S. If all else fails, count how many things you love about your life. I hope it's a long list.",
  },
  {
    id: "anniversary",
    label: "Open on a special day",
    color: "#fce8f0",
    sealColor: "#b5365a",
    ribbonColor: "#e8789a",
    content: [
      "My Arthur,",
      "Some days deserve to be marked. To be honored.",
      "Today is one of them.",
      "Thank you for being exactly who you are. For choosing me. For making this — us — something worth celebrating.",
      "I don't always say it the right way, but I want you to know: you have changed my life in the best way. You've made me braver, softer, more myself.",
      "Here's to every day we've already had, and every one we still get.",
      "I love you more than you probably know, and I'm going to spend a long time making sure you do.",
      "Forever yours,",
      "Cindy",
    ],
    ps: "P.S. You are my favorite story.",
  },
  {
    id: "need-smile",
    label: "Open when you need a smile",
    color: "#edf8ee",
    sealColor: "#3a8a4a",
    ribbonColor: "#80c890",
    content: [
      "Hello, handsome,",
      "Here are some things I love about you, in no particular order:",
      "The face you make when something surprises you. The way you get genuinely excited about things. How you always try to do the right thing even when it's hard. The fact that you're reading a letter from me right now.",
      "Also — I find you ridiculously cute and I hope that's embarrassing to read.",
      "You are a good person, Arthur. Really, truly good. And the world needs more of that.",
      "I hope this letter did its job. Now go have a wonderful day.",
      "Yours, always smiling when I think of you,",
      "Cindy",
    ],
    ps: "P.S. Hi. I love you. Okay, bye.",
  },
  {
    id: "future",
    label: "Open when you think about our future",
    color: "#f8f0fe",
    sealColor: "#8b3fa8",
    ribbonColor: "#c090e0",
    content: [
      "Dearest Arthur,",
      "So you're thinking about what comes next for us.",
      "Me too. All the time.",
      "I think about the places we'll explore. The inside jokes we haven't made yet. The mornings where neither of us has anywhere to be. The hard seasons we'll navigate together and come out stronger from.",
      "I don't know every detail of what our future looks like. But I know who I want in it.",
      "I want you in the mundane Tuesday afternoons. In the big life decisions. In the quiet moments where nothing extraordinary is happening but somehow everything feels right.",
      "Our story is still being written. And I can't wait to keep writing it with you.",
      "With so much love and excitement,",
      "Your Cindy",
    ],
    ps: "P.S. Whatever we build together, I know it's going to be something beautiful.",
  },
];
